version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - freeprise-network

  scheduler:
    build: .
    command: poetry run airflow scheduler
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:${POSTGRES_PASSWORD}@postgres:5432/db
    volumes:
      - ./dags:/app/airflow/dags
      - ./logs:/app/airflow/logs
    networks:
      - freeprise-network

  webserver:
    build: .
    command: poetry run scripts/entrypoint.sh
    depends_on:
      - postgres
      - scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:${POSTGRES_PASSWORD}@postgres:5432/db
    volumes:
      - ./dags:/app/airflow/dags
      - ./logs:/app/airflow/logs
    ports:
      - "8080:8080"
    networks:
      - freeprise-network

networks:
  freeprise-network:
    name: freeprise-network
