dbt_freeprise:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('PROJECT_ID') }}"
      keyfile: /home/liangma422/code/.gcp_keys/lm_key.json
      timeout_seconds: 300
      location: EU
      priority: interactive
      retries: 1
      schema: "{{ env_var('DEFAULT_SCHEMA', 'Bronze') }}"

    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('PROJECT_ID') }}"
      keyfile: /home/service_admin/.gcp_keys/freeprise-7df722cb2f31.json
      timeout_seconds: 300
      location: EU
      priority: interactive
      retries: 1
      schema: "{{ env_var('DEFAULT_SCHEMA', 'bigquery-prod-dataset') }}"

  target: dev
